import Vue from 'vue'
import App from './App.vue'
import router from './router'
import store from './renderer/store'
import ElementUI from 'element-ui'
import 'element-ui/lib/theme-chalk/index.css'
import '@/assets/css/global.css'

import VueI18n from 'vue-i18n'
import enLocale from 'element-ui/lib/locale/lang/en'
import zhLocale from 'element-ui/lib/locale/lang/zh-CN'

const messages = {
  en: {
    enLocale,
    Title: {
      Inverter: 'Inverter Outdoor Air Monitor',
      Fixed: 'Indoor Air Monitor',
      Information: 'About Version',
      Function:'Function And Switch',
      DataSheet:'Data Log',
      InParam:'Indoor Unit',
      OutParam:'Outdoor Unit',
      SetCompParam:'Set Drive Param',
      SetInEEPROM:'Set Indoor EEPROM',
      SetOutEEPROM: 'Set Outdoor EEPROM',
      BurnInEEPROM:'Burn Indoor EEPROM',
      BurnOutEEPROM: 'Burn Indoor EEPROM',
      ReadRamData:'RAM Data Monitor',
      SaveData:'Save Monitor Data',
      Table: 'EEPROM Table Data',
      SleepTemp:'Sleep Temp',
      Timer:'About Timer',
    },
    Header: {
      Port: 'Ports:',
      Start: 'Start',
      Stop: 'Stop',
      CRC32: 'CRC32 Chk:',
      EEPROMCheck: 'EEPROM Chk:',
      Version: 'Program Ver:'
    },
    IndoorInfo: {
      SetMode: 'Set Mode:',
      SetTemp: 'Set Temp:',
      RingTemp: 'Inner Ring:',
      TubeTemp: 'Inner Tube:',
      SetSpeed: 'Set Speed:',
      ActSpeed: 'Actual Speed:',
      
      OnOff: 'OnOff:',
      Blew: 'Blew:',
      BlewCold: 'Blew Cold:',
      BlewHeat: 'Blew Heat:',
      CompStatus: 'Comp Status',
      Error: 'Error:',

      Turbo: 'Turbe:',
      Eco: 'Eco:',
      Sleep: 'Sleep:',
      Timer: 'Timeing:',
      ForceEn: 'ForceEn:',
      Defrost: 'Defrost:', 
      LRSwing:'LRSwing:',
      UDSwing:'UDSwing:',
      Display:'Display:',
      Clean: 'Clean:',
      Dry:'Dry:',
      Heat: 'Heat:',
      Mute:'Mute:',
      TestMode:'TestMode:',
      TimeShrink:'Time Shrink:',
      Health: 'Health:',

      OneHour:'1 Hour:',
      TwoHour:'2 Hour:',
      ThreeHour:'3 Hour:',
      FourHour:'4 Hour:',
      FiveHour:'5 Hour:',
      SixHour:'6 Hour:',
      SevenHour:'7 Hour:',
      EightHour:'8 Hour:',

      TimeOff:'Time Off:',
      OffHour:'Left Off Hour:',
      OffMin:'Left Off Min:',
      TimeOn:'Time On:',
      OnHour:'Left On Hour:',
      OnMin:'Left On Hour:',

    },
    OutdoorInfo: {
      OutdoorOk: 'Outdoor Ok',

      OutdoorMode: 'Run Mode:',
      RunTime: 'Run Time:', 
      SetFreq: 'Set Freq:',
      ActualFreq: 'Actual Freq:',
      ThreeMinsCount: 'Stop Count:',
      OutTargetSpeed: 'Target Speed:',

      OutRingTemp: 'Out Ring:',
      OutTubeTemp: 'Out Tube:',
      ExhaustTemp: 'Exhaust:',
      BackTemp: 'Return Air:',
      IPMTemp: 'IPM Temp:',
      OutActualSpeed: 'Actual Speed:',

      OutEnviromentTemp: 'Ring Prot:',
      OuterProt: 'Out Tube Prot:',
      ExhaustProt: 'Exhaust Prot:',
      AverageTemp: 'Avg Exhaust:',
      DCVoltage: 'DC Voltage:',
      CompressorCurrent: 'Comp Current:',

      EEVTargetStep: 'Target EEV:',
      EEVActualStep: 'Actual EEV:',
      ValveCompensation: 'Value Diff:',
      ValveInitStep: 'Value Init:',
      ACVoltage: 'AC Voltage:',
      ACCurrent: 'AC Current:',

      DesiccantTemp: 'Desi Temp:',
      FrostTemp: 'Frost Temp:',
      FrostStage: 'Frost Grade:',
      Deforst: 'Deforst:',
      PhaseCrtProt: 'Phase Curr Prot:',
      ACCrtProt: 'AC Curr Prot:',

      TestMode: 'Test Mode:',
      Heat: 'Heat Belt:',
      FreqPoint: 'Freq Test:',
      FreqOffset: 'Freq Shift:',
      InnerProt: 'In Tube Port:',
      RelativeCtl: 'Rela Ctrl:',


      FourwayValve: 'FourWay:',
      PFC: 'PFC Status:',
      TwowayValve:'TwoWay:',
      TorqueCompensation: 'Torque:',

      CommpFreq: 'Commp Freq:',
      OutFan: 'Out Fan:',
      DriveErr: 'Drive Err:',
      SystemErr: 'System Err:'
    
    },
    SettingInfo: {
      UserTestMode: 'User Test Mode',
      Compressor: 'compressor',
      CompressorFreq: 'Frequency',
      OutdoorFan: 'Outdoor fan',
      FanType: 'Fan Type:',
      DCFan: 'DC fan',
      ACFan: 'AC fan',
      ACFanGear: 'AC Fan:',
      Stop: 'Stop',
      Low: 'Low wind',
      High: 'High wind',
      DCFanSpeed: 'DC Fan:',
      FourwaySwt: 'Four-Way',
      PFCSwt: 'PFC Switch',
      HeatbeltSwt: 'Two-Way',
      TorqueSwt: 'Torque',
      ExpansionValve: 'EEV',
      IndoorFan: 'In Fan',
      SendTestParam: 'Set Param',

      ParamType: 'Param Type:',
      DriveParam:'Drive',
      SystemParam:'System',
      ParamNumber:'Data Num:',
      ParamAdress:'Data Addr:',
      ParamPassword:'Password:',
      ParamData1:'Data1:',
      ParamData2:'Data2:',
      ParamData3:'Data3:',
      ParamSend:'Send Data',

      EEPROMInfo: 'EEPROM:',
      DriveChk: 'Drive Chk:',
      SystemChk: 'System Chk:',
      LoadPassword: 'Password:',
      LoadBar: 'Progress:',
      LoadButton: 'Load File',
      BurnButton: 'Burn File',

      Addr1: 'RAM Addr1:',
      Data1: 'RAM Data1:',
      Addr2: 'RAM Addr2:',
      Data2: 'RAM Data2:',
      Addr3: 'RAM Addr3:',
      Data3: 'RAM Data3:',
      Addr4: 'RAM Addr4:',
      Data4: 'RAM Data4:',
      Addr5: 'RAM Addr5:',
      Data5: 'RAM Data5:',

      SaveEnable: 'Save Data:',
      SaveInfo:'Data File:',
      SaveButton:'Save File',
      SaveTip:' Click <Save File> to add a data file, and then open the data save function!',

      TempCurve: 'Temp Curve:',
      TempCurveBt: 'Open Curve',
      SysCurve: 'System Curve:',
      SysCurveBt: 'Open Curve',

      Clearinfotext: 'Clear Data Text'
    },
    fault: {
      Fault: 'Fault Protection',
      IndoorNG: 'Input Failure',
      OutdoorNG: 'Out Failure',
      DriveNG: 'Drive Failure',
    },
    settings: {
      time: 'Current time',
      passwordNG: 'Password Error',
      addressNG: 'Address Error!',
      sendOK: 'Send Data Ok!',
      sendNG: 'Send Data NG!',
      tip: 'Please enter password',
      addrtip: 'Ten Binary',
      Inaddrtip: '',
      warn: 'Prompt',
      path: 'Save the data file path',
      change: 'Modify the path',
      lang: 'Language',
      true: 'Confirm',
      cancel: 'Cancel',
      clean: 'Clean History',
      reset: 'Reset',
      xlsx: 'Store Data',
      xlsxTip: 'Please enter the data save path',
      noConnect: 'SerialPort No Connect'
    },
    placeholder: {
      file: 'Please select file',
      com: 'None'
    },
    serialData: {
      open: 'Open',
      close: 'Close',
      shutdown:'Off',  
      cold: 'Cold', 
      wind: 'Wind',  
      dry: 'Dry',  
      heat: 'Heat',   
      stop: 'Stop',
      low: 'Low',
      auto: 'Auto',
      middle: 'Middle',
      high: 'High',
      indoorPro1: 'Indoor Fan Protection ',
      indoorPro2:'Fault of Indoor Secondary Tube Temperature Sensor ',
      indoorPro3:'Communication failure ',
      indoorPro4:'Indoor EEPROM fault ',
      indoorPro5:'Fault of Indoor Fan ',
      indoorPro6:'Fault of Indoor Temperature Sensor ',
      indoorPro7:'Indoor coil sensor failure ',
      normal:'Normal',
      error:'Error',
      rise:'Slow rise',
      keep:'Keep',
      slow:'Slow fall',
      fast:'Fast descending',
      down:'Shut down',
      outdoorPro1:'PFC protection ',
      outdoorPro2:'Outdoor EEPROM fault ',
      outdoorPro3:'Voltage protection ',
      outdoorPro4:'System exception ',
      outdoorPro5:'Exhaust fault ',
      outdoorPro6:'External temperature fault ',
      outdoorPro7:'External fault ',
      outdoorPro8:'Communication failure ',
      drivePro1:'DC Bus Overvoltage Protection ',
      drivePro2:'DC Bus Voltage Overlow Protection ',
      drivePro3:'Failure of Compressor Start-up ',
      drivePro4:'Failure of Compressor IPM Fo ',
      drivePro5:'Compressor peak overcurrent fault ',
      drivePro6:'Compressor Offset Fault ',
      drivePro7:'PFC offset fault ',
      drivePro8:'PFC fault ',
      drivePro9:'Comp Phase Err',
      drivePro10:'Comp Out of Step Err',
      drivePro15:'Drive Lost Voltage ',

      outdoorErr1:'Outdoor Drive Prot',
      outdoorErr2:'DC Fan Err',
      outdoorErr3:'AC Fan Err',
      outdoorErr4:'Comp Drive Err',
      outdoorErr5:'Outdoor Err Lock',
      outdoorErr6:'IPM Temp Err',

      ConvFreqHangUp: 'Conv Freq Hanging',
      FixedFreqHangUp: 'Fixed Freq Hanging',
      ConvFreqCabinet: 'ConvFreqCabinet',
      FixedFreqCabinet: 'Fixed Freq Cabinet',
    },
    ErrorAndProtect: {
      CommErr: 'Communication Failure',
      ModelErr: 'Model Configuration Error',
      OutCurrSensoeErr:'Outdoor Current Sensor Failure',
      InCoilErr: 'Inner Coil Sensor Failure',
      SystemErr: 'System Failure(Fluorine Deficiency)',
      OutDCFanErr: 'Outdoor DC Fan Fault',
      InEnvSensorErr: 'Internal Environment Temperature Sensor Failure',
      OutCoilErr: 'Failure Of Outdoor Coil Temperature Sensor',
      OutDCFanProt: 'Outdoor DC Fan Protection',
      InFanErr: 'Internal Fan Fault',
      OutModulesCommErr: 'Communication Failure Between Outdoor Modules',
      OutIPMProt: 'Outdoor IPM Protection',
      InEepromErr: 'Internal Eeprom Fault',
      InCommErr: 'Indoor And Outdoor Communication Failure',
      OutCompDriveProt: 'Outdoor Compressor Drive Protection',
      InAndOutCommErr: 'Indoor And Outdoor Communication Failure',
      OutCurrProt: 'Outdoor Current Protection',
      OutEnvHighTempProt: 'Outdoor Ambient Temperature Is Too High',
      DispCommErr: 'Communication Failure Between Display Screen And Main Control Board',
      OutVoltHLProt: 'Outdoor Protection With High Or Low Voltage',
      InCoilHeatErr: 'Indoor Coil Heating And Overheating',
      EjectionCommErr: 'Failure Of Ejection And Main Control Board Communication',
      OutSuctionSensorErr: 'Outdoor Suction Sensor Failure',
      OutCoilVoerHeatErr: 'Outdoor Coil Cooling And Overheating',
      OutIPMErr: 'Outdoor IPM Module Failure',
      OutVoltSensorErr: 'Voltage Sensor Failure',
      InCoilVoerCoolErr: 'Indoor Coil Unit Refrigeration Undercooling Protection',
      OutExhaustSensorErr: 'Failure Of Outdoor Exhaust Temperature Sensor',
      OutCompTopErr: 'Shell Top Failure Of Outdoor Compressor',
      OutExhaustHighErr: 'Outdoor Exhaust Temperature Is Too High',
      OutEvnSensorErr: 'Outdoor Temperature Sensor Failure',
      OutEepromErr: 'Outdoor Eeprom Fault',
      PFCProt: 'Outdoor Pfc Protection',
      OutCompDriveErr: 'Outdoor Compressor Drive Failure',
    },
    ErrorAndProtect2: {
      OutCompTopErr: 'OutCompTopErr',
      DispCommErr:'DispCommErr',
      InAndOutCommErr:'InAndOutCommErr',
      InEepromErr:'InEepromErr',
      InFanErr:'InFanErr',
      InEnvSensorErr:'InEnvSensorErr',
      InCoilErr:'InCoilErr',

      ErrIOComm:'IO Comm Err',
      ErrOComm:'Out Comm Err',
      ErrMatch:'Match Err',
      ErrOATSensor:'OAT Sensor Err',
      ErrOHTSensor:'OHT Sensor Err',
      ErrEEPROM:'Out EEPROM Err',
      ProtCoolMode:'Cool Mode Prot',
      ErrOBTSensor:'OBT Sensor Err',

      ProtOHTSensor	:'OHT Sensor Prot',
      ProtOPTSensor:'OPT Sensor Prot',
      ProtOATSensor	:'OAT Sensor Prot',
      ProtOATLoSensor:'OAT Low Sensor Prot',
      ProtVoltage:'Voltage Prot',
      ProtLoVoltage:'Low Voltage Prot',
      ProtHeatMode:'Heat Mode Prot',
      ErrOPTSensor:'OPT Sensor Err',

      ProtDriver:'Driver Prot',
      ProtOFan:'Out Fan Prot',
      ProtPFC:'Out PFC Prot',
      ProtCurrent:'Out Current Prot',
      ProtCompCurrent:'Comp Current Prot',
      ProtIPM:'IPM Prot',
      ProtHiBusVoltage:'High Bus Voltage Prot',
      ProtLoBusVoltage:'Low Bus Voltage Prot',

      ErrCurrentSamp:'Current Samp Err',
      ErrOpenPhase:'Open Phase Err',
      ErrOverCurrent:'Over Current Err',
      ErrIPM:'IPM Fo Err',
      ErrStepOut:'Step Out Err',
      ErrOverSpeed:'Over Speed Err',
      ErrOFan:'Out Fan Err',
      ErrPFC:'PFC Err'		
    }
  },
  zh: {
    zhLocale,
    Title: {
        Inverter: '变频室外机监控',
        Fixed: '室内机监控',
        Information: '关于版本',
        Function:'功能有无及开关',
        DataSheet:'数据日志',
        InParam:'室内机参数',
        OutParam:'室外机参数',
        SetCompParam:'修改驱动参数',
        SetInEEPROM:'修改内机EEPROM',
        SetOutEEPROM: '修改外机EEPROM',
        BurnInEEPROM:'烧写内机EEPROM',
        BurnOutEEPROM: '烧写外机EEPROM',
        ReadRamData:'监控RAM数据',
        SaveData:'数据曲线与保存',
        Table: 'EEPROM表格数据',
        SleepTemp:'睡眠温度',
        Timer:'定时开关机',
    },
    Header: {
      Port: '端口:',
      Start: '连接',
      Stop: '断开',
      CRC32: 'CRC32检验:',
      EEPROMCheck: 'EEPROM检验:',
      Version: '程序版本:'
    },
    placeholder: {
      file: '没有选择文件',
      com: '无端口'
    },
    IndoorInfo: {
      SetMode: '内机模式:',
      SetTemp: '设定温度:',
      RingTemp: '内环温度:',
      TubeTemp: '内管温度:',
      SetSpeed: '设定风挡:',
      ActSpeed: '目标转速:', 
      OnOff: '开关状态:',
      Blew: '防吹冷风:',
      BlewCold: '余冷时间:',
      BlewHeat: '余热时间:',
      CompStatus: '压机状态:',
      Error: '故障提示:',

      Turbo: '强力开关:',
      Eco: '经济模式:',
      Sleep: '睡眠模式:',
      Timer: '定时模式:',
      ForceEn: '收氟功能:',
      Defrost: '除霜状态:', 
      LRSwing:'左右摆风:',
      UDSwing:'上下摆风:',
      Display:'数显开关:',
      Clean: '清洁功能:',
      Dry:'防霉模式:',
      Heat: '电热开关:',
      Mute:'静音开关:',
      TestMode:'测试模式:',
      TimeShrink:'缩时模式:',
      Health: '健康功能:',

      OneHour:'第1小时:',
      TwoHour:'第2小时:',
      ThreeHour:'第3小时:',
      FourHour:'第4小时:',
      FiveHour:'第5小时:',
      SixHour:'第6小时:',
      SevenHour:'第7小时:',
      EightHour:'第8小时:',

      TimeOff:'定时关机:',
      OffHour:'关机剩余小时:',
      OffMin:'关机剩余分钟:',
      TimeOn:'定时开机:',
      OnHour:'开机剩余小时:',
      OnMin:'开机剩余分钟:',
    },
    OutdoorInfo: {
      OutdoorOk: '变频准备:',

      OutdoorMode: '运行模式:',
      RunTime: '运行时间:', 
      SetFreq: '设定频率:',
      ActualFreq: '实际频率:',
      ThreeMinsCount: '停机倒数:',
      OutTargetSpeed: '目标转速:',

      OutRingTemp: '外环温度:',
      OutTubeTemp: '外管温度:',
      ExhaustTemp: '排气温度:',
      BackTemp: '回气温度:',
      IPMTemp: 'IPM温度:',
      OutActualSpeed: '实际转速:',

      OutEnviromentTemp: '外环保护:',
      OuterProt: '外盘保护:',
      ExhaustProt: '排气保护:',
      AverageTemp: '平均排气:',
      DCVoltage: '母线电压:',
      CompressorCurrent: '压机电流',

      EEVTargetStep: '阀目标值:',
      EEVActualStep: '阀当前值:',
      ValveCompensation: '阀补偿值:',
      ValveInitStep: '初期阀值:',
      ACVoltage: 'AC电压:',
      ACCurrent: 'AC电流:',

      FrostTemp: '结霜温度:',
      FrostStage: '除霜阶段:',
      Deforst: '除霜状态:',
      DesiccantTemp: '除湿温度:',
      PhaseCrtProt: '相电流保护:',
      ACCrtProt: 'AC电流保护:',
     
      Heat: '加热带:',
      TestMode: '测试模式:',
      FreqPoint: '频率测试:',
      FreqOffset: '频率偏移:',
      InnerProt: '内盘保护:',
      RelativeCtl: '相对领域:',
  
      FourwayValve: '四通阀:',
      PFC: 'PFC开关:',
      TwowayValve: '二通阀:',
      TorqueCompensation: '力矩补偿:',

      CommpFreq: '压机频率:',
      OutFan: '外机风速:',   
      DriveErr: '驱动故障:',
      SystemErr: '系统故障:'
    },
    SettingInfo: {
      UserTestMode: '用户测试模式',
      Compressor: '压缩机',
      CompressorFreq: '压缩机频率',
      OutdoorFan: '选择室外风机',
      FanType: '室外风机类型',
      DCFan: '直流风机',
      ACFan: '交流风机',
      ACFanGear: '交流风机档位',
      Stop: '停止',
      Low: '低速',
      High: '高速',
      DCFanSpeed: '直流风机转速',
      FourwaySwt: '四通阀开关',
      PFCSwt: 'PFC开关',
      HeatbeltSwt: '二通阀开关',
      TorqueSwt: '转矩补偿开关',
      ExpansionValve: '膨胀阀',
      IndoorFan: '内风机',
      SendTestParam: '发送测试参数',

      ParamType: '参数类型:',
      DriveParam:'压缩机驱动参数',
      SystemParam:'系统参数',
      ParamNumber:'数据个数:',
      ParamAdress:'数据地址:',
      ParamPassword:'校验密码:',
      ParamData1:'输入数据1:',
      ParamData2:'输入数据2:',
      ParamData3:'输入数据3:',
      ParamSend:'发送参数数据',

      EEPROMInfo: 'EEPROM:',
      DriveChk: '驱动校验和:',
      SystemChk: '系统检验和:',
      LoadPassword: '烧录密码:',
      LoadBar: '烧录进度:',
      LoadButton: '加载文件',
      BurnButton: '烧录文件',
      
      Addr1: 'RAM地址1:',
      Data1: 'RAM数据1:',
      Addr2: 'RAM地址2:',
      Data2: 'RAM数据2:',
      Addr3: 'RAM地址3:',
      Data3: 'RAM数据3:',
      Addr4: 'RAM地址4:',
      Data4: 'RAM数据4:',
      Addr5: 'RAM地址5:',
      Data5: 'RAM数据5:',

      SaveEnable: '数据保存功能:',
      SaveInfo:'数据文件名称:',
      SaveButton:'保存文件',
      SaveTip:'点击<保存文件>添加数据文件，再打开数据保存功能！',

      TempCurve: '温度变化曲线:',
      TempCurveBt: '打开温度曲线',
      SysCurve: '系统参数曲线:',
      SysCurveBt: '打开参数曲线',

      Clearinfotext: '清空数据日志'

    },


    fault: {
      Fault: '故障保护',
      IndoorNG: '内机故障',
      OutdoorNG: '外机故障',
      DriveNG: '驱动故障保护',
 
    },
    testmode: {
     
    },
    monitor: {
      Addr1: 'RAM地址1',
      Data1: 'RAM数据1',
      Addr2: 'RAM地址2',
      Data2: 'RAM数据2',
      Addr3: 'RAM地址3',
      Data3: 'RAM数据3',
      Addr4: 'RAM地址4',
      Data4: 'RAM数据4',
      Addr5: 'RAM地址5',
      Data5: 'RAM数据5',
    },
    seteeprom: {
      SetE2Data:'设置EEPROM数据',
      ModifyE2Data:'修改EEPROM数据',
      SelectParam:'参数类型',
      
      
    },
    loadeeprom: {
      BurnE2Data: '烧写EEPROM Bin 数据',
      LoadFile: '加载文件',
      DriveCheck: '驱动校验和',
      SystemCheck: '系统校验和',
      BurnPassword: '校验密码',
      BurnButton: '烧写文件'
    },
  
    settings: {
      time: '当前时间',
      tip: '请输入密码',
      addrtip: '输入十进制',
      Inaddrtip: '地址：0x10~0xAF',
      warn: '提示',
      sendOK: '发送数据成功!',
      sendNG: '发送数据失败!',
      passwordNG: '密码错误!',
      addressNG: '地址错误!',
      path: '数据文件保存路径',
      change: '修改路径',
      lang: '语言',
      true: '确定',
      cancel: '取消',
      clean: '清除历史',
      reset: '复位',
      xlsx: '保存数据',
      xlsxTip: '请输入数据保存路径',
      noConnect: '没连接串口!',
    },
    serialData: {
      open: '开启',
      close: '关闭',
      shutdown:'关机',  
      cold: '制冷', 
      wind: '送风',  
      dry: '除湿',  
      heat: '制热',   
      auto: '自动',
      stop: '停止',
      low: '低风速',
      middle: '中风速',
      high: '高风速',
      indoorPro1: '内风机保护 ',
      indoorPro2:'内管故障 ',
      indoorPro3:'通讯故障 ',
      indoorPro4:'室内EE故障 ',
      indoorPro5:'内风机故障 ',
      indoorPro6:'内环故障 ',
      indoorPro7:'内盘故障 ',
      normal:'正常',
      error:'故障',
      rise:'慢升',
      keep:'保持',
      slow:'慢降',
      fast:'快降',
      down:'停机',
      outdoorPro1:'PFC保护 ',
      outdoorPro2:'室外EE故障 ',
      outdoorPro3:'电压保护 ',
      outdoorPro4:'系统异常 ',
      outdoorPro5:'排气故障 ',
      outdoorPro6:'外温故障 ',
      outdoorPro7:'外盘故障 ',
      outdoorPro8:'通讯故障 ',

      drivePro1:'母线过高 ',
      drivePro2:'母线过低 ',
      drivePro3:'压机启动失败 ',
      drivePro4:'压机IPM Fo ',
      drivePro5:'压机峰值过流 ',
      drivePro6:'压机偏置故障 ',
      drivePro7:'PFC偏置故障 ',
      drivePro8:'PFC Fo故障 ',
      drivePro9:'压机失步故障 ',
      drivePro10:'压机欠相故障 ',
      drivePro15:'驱动欠压故障 ',

      outdoorErr1:'室外驱动保护 ',
      outdoorErr2:'直流风机故障 ',
      outdoorErr3:'交流风机故障 ',
      outdoorErr4:'压机驱动故障 ',
      outdoorErr5:'室外故障锁定 ',
      outdoorErr6:'IPM温度故障 ',

      ConvFreqHangUp: '变频挂机',
      FixedFreqHangUp: '定频挂机',
      ConvFreqCabinet: '变频柜机',
      FixedFreqCabinet: '定频柜机',
    },
    ErrorAndProtect: {
      CommErr: '串口通讯故障',
      ModelErr: '机型配置错误',
      OutCurrSensoeErr:'外电流故障',
      InCoilErr: '内盘故障',
      SystemErr: '系统故障',
      OutDCFanErr: '外直流风机故障',
      InEnvSensorErr: '内环故障',
      OutCoilErr: '外盘故障',
      OutDCFanProt: '外直流风机保护',
      InFanErr: '内风机故障',
      OutModulesCommErr: '外模块通讯故障',
      OutIPMProt: '室外IPM保护',
      InEepromErr: '内EE故障',
      InCommErr: '通信故障',
      OutCompDriveProt: '压机驱动保护',
      InAndOutCommErr: '通讯故障',
      OutCurrProt: '室外电流保护',
      OutEnvHighTempProt: '外环过高',
      DispCommErr: '显示屏与主控板通讯故障',
      OutVoltHLProt: '室外电压过高或低',
      InCoilHeatErr: '内盘制热过热',
      EjectionCommErr: '顶出风和主控板通讯故障',
      OutSuctionSensorErr: '外吸气故障',
      OutCoilVoerHeatErr: '外盘制冷过热',
      OutIPMErr: 'IPM模块故障',
      OutVoltSensorErr: '外电压故障',
      InCoilVoerCoolErr: '内盘制冷过冷',
      OutExhaustSensorErr: '外排故障',
      OutCompTopErr: '室外压缩器壳顶故障',
      OutExhaustHighErr: '外排过高',
      OutEvnSensorErr: '外环故障',
      OutEepromErr: '室外EE故障',
      PFCProt: 'PFC保护',
      OutCompDriveErr: '压机驱动故障',
    },
    ErrorAndProtect2: {
      OutCompTopErr: '顶出风和主板通信故障',
      DispCommErr:'显示屏和主板通信故障',
      InAndOutCommErr:'通信故障',
      InEepromErr:'内EE故障',
      InFanErr:'内风机故障',
      InEnvSensorErr:'内环故障',
      InCoilErr:'内盘故障',

      ErrIOComm:'室内外通信故障',
      ErrOComm:'室外模块间通信故障',
      ErrMatch:'机型配置故障',
      ErrOATSensor:'室外环境温度传感器故障',
      ErrOHTSensor:'室外排气温度传感器故障',
      ErrEEPROM:'室外EEPROM故障',
      ProtCoolMode:'室内盘管制冷过冷保护',
      ErrOBTSensor:'室外吸气传感器故障',

      ProtOHTSensor	:'室外排气温度过高保护',
      ProtOPTSensor:'室外盘管制冷过热保护',
      ProtOATSensor	:'室外环境温度过高过低保护',
      ProtOATLoSensor:'室外环境温度过低过低保护',
      ProtVoltage:'室外电压过压保护',
      ProtLoVoltage:'室外电压欠压保护',
      ProtHeatMode:'室内盘管制热过热保护',
      ErrOPTSensor:'室外盘管温度传感器故障',

      ProtDriver:'室外压缩机驱动保护',
      ProtOFan:'室外直流风机保护',
      ProtPFC:'室外PFC保护',
      ProtCurrent:'室外电流保护',
      ProtCompCurrent:'压缩机相电流保护',
      ProtIPM:'室外IPM模块保护',
      ProtHiBusVoltage:'直流母线电压过高保护',
      ProtLoBusVoltage:'直流母线电压过低保护',

      ErrCurrentSamp:'压缩机相电流回路采样故障',
      ErrOpenPhase:'压缩机启动故障（断相、逆相）',
      ErrOverCurrent:'压缩机相电流过流故障',
      ErrIPM:'变频模块IPM Fo故障',
      ErrStepOut:'压缩机失步故障',
      ErrOverSpeed:'压缩机过速故障',
      ErrOFan:'外风机故障',
      ErrPFC:'PFC故障'		
    }
  }
}

Vue.use(VueI18n)
Vue.use(ElementUI, {
  i18n: (key, value) => i18n.t(key, value)
})

// Create VueI18n instance with options
const i18n = new VueI18n({
  locale: store.state.SystemData.MonitorLocale, // set locale
  messages // set locale messages
})

Vue.config.productionTip = false

new Vue({
  render: h => h(App),
  router,
  store,
  i18n
}).$mount('#app')
